/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment;

import java.awt.Color;

/**
 *
 * @author sengk
 */
public class ForgotpasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ForgotpasswordFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        txtboxUsername = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        txtboxPassword = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        txtboxConfirmPasswrord = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 2000));
        setUndecorated(true);
        setResizable(false);

        jPanelTop.setBackground(new java.awt.Color(255, 204, 102));
        jPanelTop.setForeground(new java.awt.Color(51, 51, 255));

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        txtboxUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtboxUsername.setForeground(java.awt.Color.gray);
        txtboxUsername.setText("Enter the username...");
        txtboxUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtboxUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtboxUsernameFocusLost(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(0, 0, 0));
        btnChangePassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("CHANGE PASSWORD");
        btnChangePassword.setBorderPainted(false);
        btnChangePassword.setMaximumSize(new java.awt.Dimension(59, 23));
        btnChangePassword.setMinimumSize(new java.awt.Dimension(59, 23));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        txtboxPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtboxPassword.setForeground(java.awt.Color.gray);
        txtboxPassword.setText("Enter New Password");
        txtboxPassword.setEchoChar((char)0);
        txtboxPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtboxPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtboxPasswordFocusLost(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblLogin.setText("Forgot Password");

        txtboxConfirmPasswrord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtboxConfirmPasswrord.setForeground(java.awt.Color.gray);
        txtboxConfirmPasswrord.setText("Enter New Password");
        txtboxConfirmPasswrord.setEchoChar((char)0);
        txtboxConfirmPasswrord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtboxConfirmPasswrordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtboxConfirmPasswrordFocusLost(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCEL");
        btnCancel.setBorderPainted(false);
        btnCancel.setMaximumSize(new java.awt.Dimension(59, 23));
        btnCancel.setMinimumSize(new java.awt.Dimension(59, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtboxUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtboxPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(txtboxConfirmPasswrord)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblLogin)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtboxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtboxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtboxConfirmPasswrord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon Images/icons8-in-transit-64.png"))); // NOI18N

        lblCompanyName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCompanyName.setText("Courier Service");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblCompanyName))
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void txtboxUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtboxUsernameFocusGained
        if ( txtboxUsername.getText().equals("Enter the username...")) {
            txtboxUsername.setText("");
            txtboxUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtboxUsernameFocusGained

    private void txtboxUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtboxUsernameFocusLost
        
        if ( txtboxUsername.getText().equals("")) {
            txtboxUsername.setText("Enter the username...");
            txtboxUsername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtboxUsernameFocusLost

    private void txtboxPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtboxPasswordFocusGained
        String check_pass = new String(txtboxPassword.getPassword());
        if ( check_pass.equals("Enter the password...")) {
            txtboxPassword.setText("");
            txtboxPassword.setEchoChar('\u25cf');
            txtboxPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtboxPasswordFocusGained

    private void txtboxPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtboxPasswordFocusLost
        String check_pass = new String(txtboxPassword.getPassword());
        if ( check_pass.equals("")) {
            txtboxPassword.setText("Enter the password...");
            txtboxPassword.setEchoChar((char)0);
            txtboxPassword.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtboxPasswordFocusLost

    private void txtboxConfirmPasswrordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtboxConfirmPasswrordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxConfirmPasswrordFocusGained

    private void txtboxConfirmPasswrordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtboxConfirmPasswrordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxConfirmPasswrordFocusLost

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotpasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotpasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotpasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotpasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotpasswordFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtboxConfirmPasswrord;
    private javax.swing.JPasswordField txtboxPassword;
    private javax.swing.JTextField txtboxUsername;
    // End of variables declaration//GEN-END:variables
}
